#!/bin/python

#
# Copyright (c) 2021 Vasile Vilvoiu <vasi@vilvoiu.ro>
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the MIT license. See LICENSE for details.
#

import argparse
import sys


def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Indexing tool for S2 corpus')
    parser.add_argument('corpus', type=str, help='corpus directory URL (where manifest.txt file is found)')
    parser.add_argument('--archive-regex', type=str, help='regex to match against archive filenames before processing',
                        default='s2[-]corpus[-][1-9]?[0-9]{3}[.]gz')
    args = parser.parse_args()


if __name__ == '__main__':
    main()
